CC = g++

#CXXFLAGS = -Wall -fno-inline -O2 -std=c++11 -g
CXXFLAGS = -Wall -std=c++11 -O3 -march=native

INCLUDES =
LFLAGS = 
LIBS = 
SRCS = src/computeGraphlets.cpp src/Timer.cpp src/utils.cpp src/NormalDistribution.cpp src/ArgumentParser.cpp src/Graph.cpp src/Alignment.cpp src/Method.cpp src/GreedyLCCS.cpp src/LGraalWrapper.cpp src/HubAlignWrapper.cpp src/Measure.cpp src/EdgeCorrectness.cpp src/NodeCorrectness.cpp src/InducedConservedStructure.cpp src/SymmetricSubstructureScore.cpp src/ShortestPathConservation.cpp src/LargestCommonConnectedSubgraph.cpp src/LocalMeasure.cpp src/Importance.cpp src/Graphlet.cpp src/GraphletLGraal.cpp src/NodeDensity.cpp src/EdgeDensity.cpp src/MeasureCombination.cpp src/GoSimilarity.cpp src/GoAverage.cpp src/GoCoverage.cpp src/Sequence.cpp src/InvalidMeasure.cpp src/GenericLocalMeasure.cpp src/WeightedEdgeConservation.cpp src/WeightedAlignmentVoter.cpp src/HillClimbing.cpp src/SANA.cpp src/TabuSearch.cpp src/RandomAligner.cpp src/NoneMethod.cpp src/Experiment.cpp src/ParameterEstimation.cpp src/AlphaEstimation.cpp src/ComplementaryProteins.cpp src/main.cpp
OBJS = $(SRCS:.cpp=.o)
#MAIN = sana_dbg
MAIN = sana

.PHONY: depend clean

all:    $(MAIN)

$(MAIN): $(OBJS) 
	$(CC) $(CXXFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(LFLAGS) $(LIBS)

.c.o:
	$(CC) $(CXXFLAGS) $(INCLUDES) -c $<  -o $@

clean: clear_cache
	$(RM) src/*.o src/*~ *~ $(MAIN)

clear_cache:
	rm -rf matrices/autogenerated
	rm -rf tmp
	rm -rf networks/*/autogenerated

depend: $(SRCS)
	makedepend $(INCLUDES) $^

#
