CC = g++

#CXXFLAGS = -Wall -fno-inline -O2 -std=c++11 -g
CXXFLAGS = -Wall -std=c++11 -O3 -march=native

INCLUDES = 
LFLAGS = 
LIBS = 
MEASUSES_SRCS = 				 						\
	src/measures/EdgeCorrectness.cpp 					\
	src/measures/GoAverage.cpp      					\
	src/measures/GoCoverage.cpp      					\
	src/measures/InducedConservedStructure.cpp			\
	src/measures/InvalidMeasure.cpp             		\
	src/measures/LargestCommonConnectedSubgraph.cpp		\
	src/measures/Measure.cpp							\
	src/measures/MeasureCombination.cpp					\
	src/measures/NodeCorrectness.cpp                    \
	src/measures/ShortestPathConservation.cpp           \
	src/measures/SymmetricSubstructureScore.cpp         \
	src/measures/WeightedEdgeConservation.cpp           \
	src/measures/localMeasures/EdgeDensity.cpp          \
	src/measures/localMeasures/GenericLocalMeasure.cpp  \
	src/measures/localMeasures/GoSimilarity.cpp         \
	src/measures/localMeasures/Graphlet.cpp             \
	src/measures/localMeasures/GraphletLGraal.cpp       \
	src/measures/localMeasures/Importance.cpp           \
	src/measures/localMeasures/LocalMeasure.cpp         \
	src/measures/localMeasures/NodeDensity.cpp          \
	src/measures/localMeasures/Sequence.cpp			
	
METHODS_SRC =                                           \
	src/methods/GreedyLCCS.cpp                          \
	src/methods/HillClimbing.cpp                        \
	src/methods/HubAlignWrapper.cpp                     \
	src/methods/LGraalWrapper.cpp                       \
	src/methods/Method.cpp                              \
	src/methods/NoneMethod.cpp                          \
	src/methods/RandomAligner.cpp                       \
	src/methods/SANA.cpp                                \
	src/methods/TabuSearch.cpp                          \
	src/methods/WeightedAlignmentVoter.cpp              \

ARGUMENTS_SRC = 										\
	src/arguments/ArgumentParser.cpp

OTHER_SRC =                                             \
	src/Alignment.cpp                                   \
	src/AlphaEstimation.cpp                             \
	src/ComplementaryProteins.cpp                       \
	src/computeGraphlets.cpp                            \
	src/Experiment.cpp                                  \
	src/Graph.cpp                                       \
	src/main.cpp                                        \
	src/NormalDistribution.cpp                          \
	src/ParameterEstimation.cpp                         \
	src/templateUtils.cpp                               \
	src/Timer.cpp                                       \
	src/utils.cpp
	

SRCS = $(MEASUSES_SRCS) $(METHODS_SRC) $(ARGUMENTS_SRC) $(OTHER_SRC)
OBJS = $(SRCS:.cpp=.o)
#MAIN = sana_dbg
MAIN = sana

.PHONY: depend clean

all:    $(MAIN)

$(MAIN): $(OBJS) 
	$(CC) $(CXXFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(LFLAGS) $(LIBS)

.c.o:
	$(CC) $(CXXFLAGS) $(INCLUDES) -c $<  -o $@

clean: clear_cache
	$(RM) src/*.o src/*~ *~ $(MAIN)
	$(RM) $(OBJS)

clear_cache:
	rm -rf matrices/autogenerated
	rm -rf tmp
	rm -rf networks/*/autogenerated

depend: $(SRCS)
	makedepend $(INCLUDES) $^

#
