#include "defaultArguments.hpp"

vector<string> defaultArguments = {
"-g1 yeast",
"-g2 human",
"-nodecweights 4 0.1 0.25 0.5 0.15",
"-edgecweights 4 0.1 0.25 0.5 0.15",
"-goweights 1 1",
"-gofrac 1",
"-wecnodesim graphletlgraal",
"-wavenodesim nodec",
"-tinitial 5",
"-tdecay 20",
"-t 5",
"-mode multi",
"-method sana",
"-s3 1",
"-lgraaliter 1000",
"-objfuntype generic",
"-tnew 3",
"-iterperstep 10000000",
"-numcand 3",
"-tcand 1",
"-tfin 3",
"-qcount 1",
"-o sana",
"-ntabus 300",
"-nneighbors 50",
"-qmode normal",
"-simFormat 1",
"-score sum",
"-sec 0",
"-ciq 1 -multialign 4 RNorvegicus SPombe CElegans MMusculus"
};
