#include "defaultArguments.hpp"

vector<string> defaultArguments = {
"-nodecweights 4 0.1 0.25 0.5 0.15",
"-edgecweights 4 0.1 0.25 0.5 0.15",
"-goweights 1 1",
"-gofrac 1",
"-wecnodesim graphletlgraal",
"-wavenodesim nodec",
"-tinitial auto",
"-tdecay auto",
"-schedulemethod auto",
"-mode normal",
"-method sana",
"-s3 0",
"-js 0",
"-lgraaliter 1000",
"-objfuntype generic",
"-tnew 3",
"-iterperstep 10000000",
"-numcand 3",
"-tcand 1",
"-tfin 3",
"-qcount 1",
"-o sana",
"-localScoresFile sana",
"-ntabus 300",
"-nneighbors 50",
"-qmode normal",
"-combinedScoreAs sum",
"-sec 0",
"-maxGraphletSize 5",
"-paretoInitial 1",
"-paretoCapacity 200",
"-paretoIterations 10000",
"-paretoThreads 1",
"-multipartite 1",
"-ms3_numer default", 
"-ms3_denom default"
};
