CC = g++

CXXFLAGS = -I "../../src/utils" -U__STRICT_ANSI__ -Wall -std=c++11 -O3 #-static
INCLUDES =
LFLAGS =
LIBS =

SRC = 							\
	createShadow.cpp

SRCS = $(SRC)
OBJDIR = _objs
OBJS = $(addprefix $(OBJDIR)/, $(SRCS:.cpp=.o))

MAIN = createShadow

all: $(MAIN)

$(MAIN): $(OBJS)
	$(CC) $(CXXFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJDIR)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(CC) -c $(INCLUDES) -o $@ $< $(CXXFLAGS)

clean:
	rm -f *.core
	rm -f createShadow
	rm -r -f _objs/
