#ifndef UTILS_H
#define UTILS_H
#include <vector>
#include <map>
#include <ostream>
#include <unordered_map>
#include "stdiobuf.hpp"
#include "templateUtils.cpp"

using namespace std;

//Auxiliary functions oblivious to SANA or network alignment but that can come helpful.

//folder where any part of the codebase can save autogenerated files
extern const string AUTOGENEREATED_FILES_FOLDER;

typedef uint16_t ushort;
typedef uint32_t uint;

double randDouble();
int randInt(int low, int high);
int randMod(int n);

vector<uint> reverseMapping(const vector<uint>& map, int range);

int min(int a, int b);
int max(int a, int b);

double vectorMean(const vector<double>& v);
double vectorMax(const vector<double>& v);
double vectorMin(const vector<double>& v);
double vectorSum(const vector<double>& v);

void randomShuffle(vector<uint>& v);
void randomShuffle(vector<vector<string>>& v);

void printTable(const vector<vector<string>>& table, int colSeparation, ostream& stream);

const string currentDateTime();

void normalizeWeights(vector<double>& weights);

FILE* decompressFile(const string& decompProg, const string& fileName);

vector<string> fileToStrings(const string& fileName, bool asLines = false);
vector<vector<string> > fileToStringsByLines(const string& fileName);
void memExactFileParseByLine(vector<vector<string> >& result, const string& fileName);

string extractDecimals(double value, int count);

bool fileExists(const string& filename);
void checkFileExists(const string& filename);
void addUniquePostfixToFilename(string& name, const string& extension);

stdiobuf readFileAsStreamBuffer(const string& fileName);
FILE* readFileAsFilePointer(const string& fileName, bool& piped);
void closeFile(FILE* fp, const bool& isPiped);
string getDecompressionProgram(const string& fileName);
string getUncompressedFileExtension(const string& fileName);

void skipWordInStream(istream& is, const string& str);
bool canSkipWordInStream(istream& is, const string& str);

bool folderExists(string folderName);
void createFolder(string folderName);

string exec(string cmd);
string execWithoutPrintingErr(string cmd);
void execPrintOutput(string cmd);

void deleteFile(string name);

void writeDataToFile(const vector<vector<string>>& data, string fileName, bool useTabs = false);

//if the file ends in '\n', it counts as a new line
uint numLinesInFile(const string& fileName);

uint factorial(uint n);
uint binomialCoefficient(uint n, uint k);
double binomialCoefficientFloat(uint n, uint k);

vector<string> getFilesInDirectory(const string &directory);
string autocompleteFileName(const string dir, const string fileNamePrefix);

string toLowerCase(string s);

string extractFileName(string s);
string extractFileNameNoExtension(string s);

vector<string> removeDuplicates(const vector<string>& v);

vector<string> split(const string& s, char c);


bool newerGraphAvailable(const char* graphDir, const char* binaryDir);
pair<unsigned, unsigned> countVecLens(string& fileName);

unordered_map<uint,uint> getReverseMap(const unordered_map<uint,uint>& reverse);

#endif /* UTILS_H */