#!/bin/sh
# add numbers, one per LINE
sed 's/#.*//' "$@" | awk '{for(i=1;i<=NF;i++)sum+=$i}END{print sum}'
exit
newlines "$@" | sed '/^[    ]*$/d' |
    sed '2,$s/$/+/
    $s/$/p/' |
    sed 's/-/_/' | dc
