#!/bin/sh
[ -d /dev/cpu ] && ls -F /dev/cpu | fgrep -c /
([ `arch` = Darwin -o `uname` = Darwin ] || uname -a | grep Darwin >/dev/null) && sysctl -n hw.ncpu

case `arch` in
CYGWIN*) grep -c '^processor[ 	]*:' /proc/cpuinfo ;;
esac
