#!/bin/sh
for i
do
    case "$i" in
    *.el) awk '{node[$1]=node[$2]=1;numEdges++}END{for(i in node)numNodes++; print numEdges}' "$i" ;;
    *.gw) awk '/^[0-9][0-9]*$/{if(nodes)print;else nodes=1}' "$i" ;;
    esac
done
