#!/bin/sh
SEED=-1
case "$1" in
-s) SEED="$2"; shift 2;;
esac

DIR=`dirname $0`
PATH="$DIR:$DIR/../NetGO:$PATH"
cat "$@" | hawk 'BEGIN{seed=1*'"$SEED"'; if(seed==-1)Srand(); else srand(seed);}
    function randint(N){return int(N*rand())}
    {line[NR]=$0}
    END{
	N=NR;
	while(N) {
	    k=randint(N)+1;
	    print line[k];
	    line[k]=line[N--];
	}
    }'
