#!/bin/sh
cat "$@" | hawk 'BEGIN{Srand()}
    function randint(N){return int(N*rand())}
    {line[NR]=$0}
    END{
	N=NR;
	while(N) {
	    k=randint(N)+1;
	    print line[k];
	    line[k]=line[N--];
	}
    }'
