// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef magnaui_h
#define magnaui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Float_Input.H>
#include <FL/Fl_Int_Input.H>
#include "magnauibase.h"

class MagnaUI {
public:
  MagnaUI();
  Fl_Double_Window *main_window;
  Fl_Button *load_graph1_btn;
private:
  inline void cb_load_graph1_btn_i(Fl_Button*, void*);
  static void cb_load_graph1_btn(Fl_Button*, void*);
public:
  Fl_Input *load_graph1_disp;
private:
  inline void cb_load_graph1_disp_i(Fl_Input*, void*);
  static void cb_load_graph1_disp(Fl_Input*, void*);
public:
  Fl_Button *load_graph2_btn;
private:
  inline void cb_load_graph2_btn_i(Fl_Button*, void*);
  static void cb_load_graph2_btn(Fl_Button*, void*);
public:
  Fl_Input *load_graph2_disp;
private:
  inline void cb_load_graph2_disp_i(Fl_Input*, void*);
  static void cb_load_graph2_disp(Fl_Input*, void*);
public:
  Fl_Button *output_dir_btn;
private:
  inline void cb_output_dir_btn_i(Fl_Button*, void*);
  static void cb_output_dir_btn(Fl_Button*, void*);
public:
  Fl_Input *output_dir_disp;
private:
  inline void cb_output_dir_disp_i(Fl_Input*, void*);
  static void cb_output_dir_disp(Fl_Input*, void*);
public:
  Fl_Input *output_prefix_disp;
private:
  inline void cb_output_prefix_disp_i(Fl_Input*, void*);
  static void cb_output_prefix_disp(Fl_Input*, void*);
public:
  Fl_Group *edge_group;
  Fl_Light_Button *edge_s3;
private:
  inline void cb_edge_s3_i(Fl_Light_Button*, void*);
  static void cb_edge_s3(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *edge_ec;
private:
  inline void cb_edge_ec_i(Fl_Light_Button*, void*);
  static void cb_edge_ec(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *edge_ics;
private:
  inline void cb_edge_ics_i(Fl_Light_Button*, void*);
  static void cb_edge_ics(Fl_Light_Button*, void*);
public:
  Fl_Group *node_group;
  Fl_Light_Button *node_none;
private:
  inline void cb_node_none_i(Fl_Light_Button*, void*);
  static void cb_node_none(Fl_Light_Button*, void*);
public:
  Fl_Lighter_Button *node_m;
private:
  inline void cb_node_m_i(Fl_Lighter_Button*, void*);
  static void cb_node_m(Fl_Lighter_Button*, void*);
public:
  Fl_Input *node_m_disp;
private:
  inline void cb_node_m_disp_i(Fl_Input*, void*);
  static void cb_node_m_disp(Fl_Input*, void*);
public:
  Fl_Float_Input *alpha_disp;
private:
  inline void cb_alpha_disp_i(Fl_Float_Input*, void*);
  static void cb_alpha_disp(Fl_Float_Input*, void*);
public:
  Fl_Group *init_pop_group;
  Fl_Light_Button *init_pop_none;
private:
  inline void cb_init_pop_none_i(Fl_Light_Button*, void*);
  static void cb_init_pop_none(Fl_Light_Button*, void*);
public:
  Fl_Lighter_Button *init_pop_file;
private:
  inline void cb_init_pop_file_i(Fl_Lighter_Button*, void*);
  static void cb_init_pop_file(Fl_Lighter_Button*, void*);
public:
  Fl_Input *init_pop_file_disp;
private:
  inline void cb_init_pop_file_disp_i(Fl_Input*, void*);
  static void cb_init_pop_file_disp(Fl_Input*, void*);
public:
  Fl_Int_Input *pop_size_disp;
private:
  inline void cb_pop_size_disp_i(Fl_Int_Input*, void*);
  static void cb_pop_size_disp(Fl_Int_Input*, void*);
public:
  Fl_Int_Input *num_gens_disp;
private:
  inline void cb_num_gens_disp_i(Fl_Int_Input*, void*);
  static void cb_num_gens_disp(Fl_Int_Input*, void*);
public:
  Fl_Float_Input *frac_elite_disp;
private:
  inline void cb_frac_elite_disp_i(Fl_Float_Input*, void*);
  static void cb_frac_elite_disp(Fl_Float_Input*, void*);
public:
  Fl_Int_Input *n_threads_disp;
private:
  inline void cb_n_threads_disp_i(Fl_Int_Input*, void*);
  static void cb_n_threads_disp(Fl_Int_Input*, void*);
public:
  Fl_Int_Input *freq_output_disp;
private:
  inline void cb_freq_output_disp_i(Fl_Int_Input*, void*);
  static void cb_freq_output_disp(Fl_Int_Input*, void*);
public:
  Fl_Button *run_sim_btn;
  Fl_Button *stop_sim_btn;
private:
  inline void cb_stop_sim_btn_i(Fl_Button*, void*);
  static void cb_stop_sim_btn(Fl_Button*, void*);
public:
  void show(int argc, char **argv);
  struct magnaparams *sim;
  static void run_sim_btn_cb(Fl_Button* o, void* v);
  void run_sim_btn_cb_i(Fl_Button*, void*);
  pthread_t run_sim_thread; 
};
#endif
