hungarian: scratch.o start.o Alignment/align.o Bionets/compute_local_subgraph.o Bounds/bounds.o Bounds/glb.o Bounds/run_bounds.o Bounds/test_glb.o Cryptographic_Hash/sha2.o Experiments/statistics.o Heuristics/dsmatrix.o Heuristics/eda.o Heuristics/new_eda.o Heuristics/run_new_eda.o Hungarian/lap_approx.o Hungarian/lap.o Hungarian/matrix.o Hungarian/munkres.o Hungarian/run_lap_approx.o Notes/bgl_notes.o Notes/stl_notes.o Prob/prob.o
	g++ -std=c++11 -o hungarian scratch.o start.o Alignment/align.o Bionets/compute_local_subgraph.o Bounds/bounds.o Bounds/glb.o Bounds/run_bounds.o Bounds/test_glb.o Cryptographic_Hash/sha2.o Experiments/statistics.o Heuristics/dsmatrix.o Heuristics/eda.o Heuristics/new_eda.o Heuristics/run_new_eda.o Hungarian/lap_approx.o Hungarian/lap.o Hungarian/matrix.o Hungarian/munkres.o Hungarian/run_lap_approx.o Notes/bgl_notes.o Notes/stl_notes.o Prob/prob.o

scratch.o: scratch.cpp
start.o: start.cpp
Alignment/align.o: Alignment/align.cpp
Bionets/compute_local_subgraph.o: Bionets/compute_local_subgraph.cpp
Bounds/bounds.o: Bounds/bounds.cpp
Bounds/glb.o: Bounds/glb.cpp
Bounds/run_bounds.o: Bounds/run_bounds.cpp
Bounds/test_glb.o: Bounds/test_glb.cpp
Cryptographic_Hash/sha2.o: Cryptographic_Hash/sha2.cpp
Experiments/statistics.o: Experiments/statistics.cpp
Heuristics/dsmatrix.o: Heuristics/dsmatrix.cpp
Heuristics/eda.o: Heuristics/eda.cpp
Heuristics/new_eda.o: Heuristics/new_eda.cpp
Heuristics/run_new_eda.o: Heuristics/run_new_eda.cpp
Hungarian/lap_approx.o: Hungarian/lap_approx.cpp
Hungarian/lap.o: Hungarian/lap.cpp
Hungarian/matrix.o: Hungarian/matrix.cpp
Hungarian/munkres.o: Hungarian/munkres.cpp
Hungarian/run_lap_approx.o: Hungarian/run_lap_approx.cpp
Notes/bgl_notes.o: Notes/bgl_notes.cpp
Notes/stl_notes.o: Notes/stl_notes.cpp
Prob/prob.o: Prob/prob.cpp

clean:
	/bin/rm -f scratch.o start.o Alignment/align.o Bionets/compute_local_subgraph.o Bounds/bounds.o Bounds/glb.o Bounds/run_bounds.o Bounds/test_glb.o Cryptographic_Hash/sha2.o Experiments/statistics.o Heuristics/dsmatrix.o Heuristics/eda.o Heuristics/new_eda.o Heuristics/run_new_eda.o Hungarian/lap_approx.o Hungarian/lap.o Hungarian/matrix.o Hungarian/munkres.o Hungarian/run_lap_approx.o Notes/bgl_notes.o Notes/stl_notes.o Prob/prob.o
