all:
	ant -f /home/davis/cytoscapealignmentdrawerplugin-code/alignmentdrawerplugin -Dnb.internal.action.name=build jar
clean:
	ant -f /home/davis/cytoscapealignmentdrawerplugin-code/alignmentdrawerplugin -Dnb.internal.action.name=clean clean
