#!/bin/sh
PATH="`pwd`/scripts:$PATH"
export PATH
DIR=/tmp/syeast.$$
EXIT_CODE=0
trap "/bin/rm -rf $DIR;"' exit $EXIT_CODE' 0 1 2 3 15
ITERS=20
minutes=2
/bin/rm -rf $DIR networks/*/autogenerated /var/preserve/autogen* /tmp/autogen* networks/*-shadow*
echo "Running $ITERS iterations of $minutes minute(s) each"
nice -19 ./multi-pairwise.sh ./sana.multi '-s3 0 -ses 1' $ITERS $minutes '-parallel 4' $DIR networks/syeast[12]?/*.el || EXIT_CODE=1
cd $DIR
rename.sh ';dir;dir0;' dir?
mv dir00 dir0 # all except this zeroth one
echo "Now check NC values: below are the number of times the multiple alignment contains k correctly matching nodes, k=2,3,4:"
echo "iter	NC2	NC3	NC4"
for d in dir??; do echo "$d" `for i in 2 3 4; do awk '{delete K;for(i=1;i<=NF;i++)++K[$i];for(i in K)if(K[i]>='$i')print}' $d/multiAlign.tsv | wc -l; done` | sed 's/ /\t/g'; done
echo "And now the Multi-NC, or MNC, measure, of the final alignment"
echo 'k	number	MNC'
for k in 2 3 4; do echo "$k	`awk '{delete K;for(i=1;i<=NF;i++)++K[$i];for(i in K)if(K[i]>='$k')nc++}END{printf "%d\t%.3f\n",nc,nc/NR}' dir$ITERS/multiAlign.tsv`"
done | tee $DIR/MNC.txt
echo "Now check that MNC values are high enough: for k=2,3,4, we want MNC 0.3, 0.2, and 0.1 respectively."
awkcel '{k=$1;expect=(0.5-k/10);if($3<expect)exit(1)}' $DIR/MNC.txt || EXIT_CODE=1
exit $EXIT_CODE
